### ISSUE TITLE
Not and issues but...

### ISSUE THREAD

**Issue by fwzmhmd** [sctigercat1/sctigercat1.github.io#1]
Is there any way i can contact you asap.

**Comment by sctigercat1** [comment]
For what reason?

**Comment by fwzmhmd** [comment]
Help with weipdcrm

**Comment by sctigercat1** [comment]
You may consider asking one of the weipdcrm devs directly (i.e. https://github.com/Hintay) who would probably be able to offer better support than I :P

**Comment by fwzmhmd** [comment]
Maybe? But just wanted to ask have you set up weipdcrm on digital ocean?

**Comment by sctigercat1** [comment]
Haven't set it up on DO explicitly but I mean it's just a linux box, right? Probably ubuntu?

If so, what was your issue?

**Comment by fwzmhmd** [comment]
It just wouldn't set up for me, i could give you ssh access but its very late for me now. We could work this out some time today.

**Comment by sctigercat1** [comment]
I'm not sure if I'll have enough time to totally debug a system during the upcoming days but maybe I could help you work though a more specific problem later?

**Comment by fwzmhmd** [comment]
It wouldnt need debugging, i just created a new droplet from scratch. It has something to do woth file permisssions

**Comment by fwzmhmd** [comment]
I don't  know which file prmission to use
